version: "3.9"

services:
  fastapi:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8022
    volumes:
      - .:/dictionary_project
    ports:
      - 8022:8022
    environment:
      - X_RAPIDAPI_HOST=${X_RAPIDAPI_HOST}
      - X_RAPIDAPI_KEY=${X_RAPIDAPI_KEY}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PWD=${MONGO_PWD}
    restart: always
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD}
    ports:
      - 27017:27017
    restart: always
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: nginx_dockerfile
  #   ports:
  #     - 1338:80
  #   depends_on:
  #     - fastapi
volumes:
  mongodb_data: